# Generated by Django 5.1.5 on 2025-01-20 02:12

import AppVehiculo.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vin', models.CharField(max_length=17, unique=True, validators=[AppVehiculo.models.validar_vin])),
                ('cis', models.CharField(max_length=8, validators=[AppVehiculo.models.validar_cis])),
                ('version', models.CharField(max_length=20)),
            ],
        ),
    ]
