# Generated by Django 5.1.5 on 2025-01-21 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppVehiculo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_extend', models.CharField(max_length=10, unique=True, verbose_name='Versión Extendida')),
                ('version_codif', models.CharField(max_length=3, unique=True, verbose_name='Código de Versión')),
                ('mercado', models.CharField(choices=[('EU', 'Europa'), ('AS', 'Asia'), ('AM', 'América'), ('AF', 'África'), ('OC', 'Oceanía')], max_length=2, verbose_name='País de Destino')),
            ],
            options={
                'verbose_name': 'Versión',
                'verbose_name_plural': 'Versiones',
                'unique_together': {('version_extend', 'version_codif')},
            },
        ),
    ]
