# Generated by Django 5.1.5 on 2025-01-21 04:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppVehiculo', '0002_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='version',
            name='mercado',
            field=models.CharField(choices=[('EU', 'Europa'), ('AS', 'Asia'), ('AM', 'América'), ('AF', 'África'), ('OC', 'Oceanía'), ('AR', 'Argentina')], max_length=2, verbose_name='País de Destino'),
        ),
        migrations.CreateModel(
            name='Proxy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('central', models.CharField(choices=[('BCM', 'Body Control Module'), ('PCM', 'Powertrain Control Module'), ('TCM', 'Transmission Control Module'), ('ECM', 'Engine Control Module'), ('ABS', 'Anti-lock Braking System')], max_length=3, verbose_name='Central')),
                ('configuracion', models.CharField(max_length=64, verbose_name='Configuración')),
                ('sw_version', models.CharField(max_length=10, verbose_name='Versión de Software')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppVehiculo.version', verbose_name='Versión')),
            ],
            options={
                'verbose_name': 'Proxy',
                'verbose_name_plural': 'Proxies',
            },
        ),
    ]
